version: "3.7"

services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www/main
            - ./logs/nginx:/var/log/nginx
        links:
            - php
    php:
        build: ./images/php
        links:
            - mysql1
        volumes:
            - ./www:/var/www/main
    mysql1:
        build: ./images/mysql1
        ports:
            - "3306:3306"
        volumes:
         - ./logs/mysql:/var/log/mysql
         - ./db/mysql:/var/lib/mysql
         - ./db/mysql-files:/var/lib/mysql-files
         - ./data:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: test
            MYSQL_DATABASE: news_db
    mysql2:
        build: ./images/mysql2
        ports:
            - "3307:3307"
        volumes:
         - ./logs/mysql2:/var/log/mysql
         - ./db/mysql2:/var/lib/mysql
         - ./db/mysql-files2:/var/lib/mysql-files
         - ./data:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: test
            MYSQL_DATABASE: news_db
    # proxysql:
    #     build: ./images/proxysql
    #     container_name: proxysql
    #     volumes:
    #       - ./db/proxysql:/var/lib/proxysql
    #     ports:
    #       # Mysql Client Port
    #       - "6033:6033"
    #       # Mysql Admin Port
    #       - "6032:6032"
    rabbitmq:
        image: rabbitmq:3.9-management-alpine
        container_name: 'rabbitmq'
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ./libs/rabbitmq:/var/lib/rabbitmq/
            - ./logs/rabbitmq:/var/log/rabbitmq/
    redis:
        image: "redis:alpine"
        command: redis-server --requirepass testpass
        ports:
            - "6379:6379"
        volumes:
            - ./libs/redis:/var/lib/redis
      #      - ./libs/redis.conf:/usr/local/etc/redis/redis.conf
        environment:
            - REDIS_REPLICATION_MODE=master
